version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: taskboard-postgres
    restart: always
    environment:
      POSTGRES_USER: MIX_admin
      POSTGRES_PASSWORD: Golden168$
      POSTGRES_DB: office_task_board
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: